// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from './application';

import PricingSwitchController from './pricing-switch-controller';
import RangeSliderController from './range-slider-controller';
import OnboardingController from './onboarding-controller';

application.register('pricing-switch', PricingSwitchController);
application.register('range-slider', RangeSliderController);
application.register('onboarding', OnboardingController);
