apiVersion: traefik.containo.us/v1alpha1
kind: IngressRoute
metadata:
  name: motherfit-http
spec:
  entryPoints:
    - web
  routes:
    - kind: Rule
      match: Host(`{{ .Values.ingress.domain }}`) || Host(`www.{{ .Values.ingress.domain }}`)
      middlewares:
        - name: redirect-to-https
      services:
      - kind: Service
        name: {{ .Release.Name }}-web
        passHostHeader: true
        port: 80
        scheme: http
