apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ .Release.Name }}-db-migrate-{{ .Values.image.tag | trunc 8 }}"
  annotations:
    helm.sh/hook: post-install, post-upgrade
    helm.sh/hook-weight: "5"
    helm.sh/hook-delete-policy: "before-hook-creation"
spec:
  ttlSecondsAfterFinished: 86400
  template:
    metadata:
      name: {{ .Release.Name }}-db-migrate
      labels:
        app: {{ .Release.Name }}-db-migrate
    spec:
      imagePullSecrets:
      - name: gitlab-pull-secret
      restartPolicy: Never
      containers:
      - name: {{ .Release.Name }}-db-migrate
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        command: ['bin/rails']
        args: ['db:migrate']
        env:
          {{- include "env" . | nindent 10 }}
