apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: redirect-to-www
spec:
  redirectRegex:
    regex: ^https://motherfit.co.uk/(.*)
    replacement: https://www.motherfit.co.uk/${1}
